name: clothiva_project
description: "Clothiva is a Flutter-based fashion e-commerce app that offers men's and women's clothing in one stylish platform."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.8.1

#--------------------------- Packages -------------------------------------#
dependencies:
  flutter:       
    sdk: flutter 
  
  # Utility Packages
  http: ^1.5.0
  intl: ^0.20.2
  logger: ^2.6.1
  url_launcher: ^6.3.2
  flutter_native_splash: ^2.4.6
  lottie: ^3.3.1
  connectivity_plus: ^7.0.0
  shimmer: ^3.0.0
  badges: ^3.1.2
  carousel_slider: ^5.1.1
  smooth_page_indicator: ^1.2.1

  
  # Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.2

  # State Management
  get: ^4.6.5
  get_storage: ^2.1.1

  # Product Specific
  flutter_rating_bar: ^4.0.1

  # Firebase
  firebase_core: ^4.1.0
  firebase_auth: ^6.0.2
  cloud_firestore: ^6.0.1


#--------------------------- ./ Packages END -------------------------------------#
dev_dependencies:
  flutter_test:    
    sdk: flutter   
  flutter_lints: ^5.0.0  # CRITICAL: Required for code quality - DO NOT REMOVE

flutter:
  uses-material-design: true # CRITICAL: - DO NOT REMOVE
  assets:
    - assets/images/
    - assets/icons/
    - assets/logos/
    - assets/icons/brands/
    - assets/images/profile/
    - assets/images/dashboard/
    - assets/images/splash_images/
    - assets/images/welcome_images/
    - assets/images/forget_password/
    - assets/images/on_boarding_images/
    - assets/images/animations/
    - assets/images/banners/
    - assets/icons/payment_methods/
    - assets/images/products/
    - assets/images/brands/
    - assets/icons/categories/
    - assets/icons/payment_methods/paypal.png
  # CRITICAL ASSET MANAGEMENT RULES:
  # - DO NOT ADD NEW ASSET DIRECTORIES (assets/svg/, assets/icons/, etc.)
  # - ONLY USE EXISTING AND ITEMS AVAILABLE IN THE DIRECTORIES LISTED ABOVE (assets/, assets/images/)
  
  # FONTS:
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300

        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400

        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic

        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500

        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic

        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600

        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800
