// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPpxLvE4uXk9UZG-I1-h_vXj4zIiUP_H4',
    appId: '1:82269750087:web:a545ded0a27fd779d74262',
    messagingSenderId: '82269750087',
    projectId: 'clothivaapp',
    authDomain: 'clothivaapp.firebaseapp.com',
    storageBucket: 'clothivaapp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBw-bz2B6vH0AVxdBVZ-oP9mLCyOEFKUSk',
    appId: '1:82269750087:android:051c7cc934476172d74262',
    messagingSenderId: '82269750087',
    projectId: 'clothivaapp',
    storageBucket: 'clothivaapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdIMT_keV9iBbOh9nUR-BJIofW6KRuzak',
    appId: '1:82269750087:ios:5ec832c624425a1ad74262',
    messagingSenderId: '82269750087',
    projectId: 'clothivaapp',
    storageBucket: 'clothivaapp.firebasestorage.app',
    androidClientId: '82269750087-bpuo933cocv0fun783rgdbkn6l35vs47.apps.googleusercontent.com',
    iosClientId: '82269750087-uv1065vo6atjr1f994emifgkgqeika2c.apps.googleusercontent.com',
    iosBundleId: 'com.example.clothivaProject',
  );

}